import { expect, it } from 'vitest';
import { Chess } from 'chess.js';
import { Game, beginnerRules, findAttack, findDanger, randomColor } from '../../src/game';
import { fromHash, gameHash } from '../../src/share';

it('supports either human color across selection, takebacks, links, and coaching', () => {
  expect(randomColor(() => 0)).toBe('w');
  expect(randomColor(() => .499)).toBe('w');
  expect(randomColor(() => .5)).toBe('b');
  expect(randomColor(() => .999)).toBe('b');
  const game = new Game(beginnerRules, 'b');
  expect(game.humanTurn).toBe(false);
  game.play('e2e4');
  const opening = game.chess.fen();
  expect(game.canUndo).toBe(false);
  game.undo(); expect(game.chess.fen()).toBe(opening);
  game.play('e7e5'); game.play('g1f3');
  expect(game.canUndo).toBe(true);
  game.undo(); expect(game.chess.fen()).toBe(opening);
  expect(game.humanTurn).toBe(true);
  game.play('c7c5'); game.undo();
  expect(game.chess.fen()).toBe(opening);
  const linked = new Game({ castling: true, enPassant: true }, 'b');
  linked.play('e2e4'); linked.play('e7e5');
  const restored = fromHash(gameHash(linked, true))!;
  expect(restored.game.humanColor).toBe('b');
  expect(restored.game.chess.fen()).toBe(linked.chess.fen());
  expect(restored.game.rules).toEqual(linked.rules);
  expect(restored.pending).toBe(true);
  expect(fromHash('#v1.AA')?.game.humanColor).toBe('w');
  expect(fromHash(gameHash(new Game(beginnerRules, 'b')))?.game.humanColor).toBe('b');
  const chess = new Chess('4k3/8/4r3/3P4/8/8/8/4K3 b - - 0 1');
  expect(findAttack(chess, beginnerRules, 'b')?.voice).toBe('attack-pawn-rook-free');
  const blunder = new Chess('4k3/4q3/8/8/3P4/8/8/4K3 b - - 0 1');
  const played = blunder.move('Qe5');
  expect(findDanger(blunder, beginnerRules, played)?.voice).toBe('blunder-queen');
  const mate = new Game(beginnerRules, 'b');
  mate.chess = new Chess('7k/6Q1/5K2/8/8/8/8/8 b - - 0 1');
  expect(mate.over).toBe('human-checkmated');
  mate.humanColor = 'w';
  expect(mate.over).toBe('ai-checkmated');
});
